"""Write the Windows version resource PyInstaller stamps into the exe (the Details tab).

    python tools/version_info.py build/version_info.txt

Everything comes from `claude_projects.__version__`, so the tag, the package metadata and the exe
cannot drift apart — `--check <tag>` fails when they do, which is what CI runs before a release.
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from claude_projects import APP_TITLE, __version__          # noqa: E402  (path set above)

COMPANY = "kimssi-labs"
COPYRIGHT = f"Copyright (c) 2026 {COMPANY}. MIT License."
DESCRIPTION = "Keyboard manager for Claude Code projects and sessions"
EXE_NAME = "ClaudeProjects.exe"
HOMEPAGE = "https://github.com/kimssi-labs/claude-projects"
LANG_EN_US, CHARSET_UNICODE = 0x0409, 1200                  # 040904B0 in the StringFileInfo key

TEMPLATE = """# Generated by tools/version_info.py — do not edit; change __version__ instead.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={parts}, prodvers={parts},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '{lang:04x}{charset:04x}',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{internal}'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', '{exe}'),
         StringStruct('ProductName', '{product}'),
         StringStruct('ProductVersion', '{version}'),
         StringStruct('Comments', '{homepage}')])
    ]),
    VarFileInfo([VarStruct('Translation', [{lang}, {charset}])])
  ]
)
"""


def version_parts(version: str) -> tuple[int, int, int, int]:
    """(major, minor, patch, 0) — the four 16-bit fields Windows wants."""
    numbers = [int(p) for p in version.split(".")]
    numbers += [0] * (4 - len(numbers))
    return tuple(numbers[:4])                               # type: ignore[return-value]


def render(version: str) -> str:
    return TEMPLATE.format(parts=version_parts(version), version=version, company=COMPANY,
                           description=DESCRIPTION, internal=APP_TITLE, copyright=COPYRIGHT,
                           exe=EXE_NAME, product=APP_TITLE, homepage=HOMEPAGE,
                           lang=LANG_EN_US, charset=CHARSET_UNICODE)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("out", nargs="?", type=Path, help="file to write (default: print)")
    ap.add_argument("--check", metavar="TAG",
                    help="fail unless TAG (v1.2.3) matches __version__ and pyproject.toml")
    a = ap.parse_args()

    if a.check:
        tag = a.check.lstrip("v")
        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        packaged = next(l.split('"')[1] for l in pyproject.splitlines() if l.startswith("version ="))
        if not (tag == __version__ == packaged):
            sys.exit(f"version mismatch — tag {tag}, __version__ {__version__}, pyproject {packaged}")
        print(f"version {tag} matches source and pyproject")
        return

    text = render(__version__)
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text, encoding="utf-8")
        print(f"wrote {a.out} for version {__version__}")
    else:
        sys.stdout.reconfigure(encoding="utf-8")
        print(text)


if __name__ == "__main__":
    main()
